version: '3'

services:
  #  db:
  #    image: postgres
  #    environment:
  #      POSTGRES_USER: postgres
  #      POSTGRES_PASSWORD: postgres
  #    healthcheck:
  #      test: ["CMD-SHELL", "pg_isready -U postgres"]
  #      interval: 5s
  #      timeout: 5s
  #     retries: 5
  #   ports:
  #     - '5432:5432'
  web:
    build: .
      #    command: python3 manage.py runserver 0.0.0.0:10000
    command: python manage.py runserver 0.0.0.0:10000
    volumes:
      - .:/code
    ports:
      - "10000:10000"
        #    depends_on:
        #      db:
        #        condition: service_healthy

